// Export all schema components from a central location
export * from './users';
export * from './xp';
export * from './profile';
export * from './matches';
export * from './ratings';
export * from './tournaments';
export * from './events';
export * from './communities';
export * from './golden-tickets';
export * from './passport';
export * from './audit';
export * from './moderation';
export * from './media';
export * from './bounce';
export * from './coach-marketplace';
export * from './coach-management';
export * from './coach-public-profiles';
export * from './student-coach-connections';