/**
 * PKL-278651-COACH-0001-CORE
 * S.A.G.E. (Skills Assessment & Growth Engine) Schema
 * 
 * This file defines the database schema for the SAGE coaching system,
 * including coaching sessions, insights, and content library.
 * 
 * @framework Framework5.3
 * @version 1.0.0
 * @lastModified 2025-04-24
 */

import { pgTable, serial, integer, text, timestamp, boolean, jsonb } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { users, matches } from "../schema";

/**
 * Coaching Sessions table
 * Stores information about coaching sessions created by SAGE
 */
export const coachingSessions = pgTable("coaching_sessions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  sessionType: text("session_type").notNull(), // "match_analysis", "assessment", "training_plan"
  title: text("title").notNull(),
  summary: text("summary"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  status: text("status").notNull().default("active"), // "active", "archived", "completed"
  relatedMatchId: integer("related_match_id").references(() => matches.id),
  metadata: jsonb("metadata").default({}).notNull(),
});

/**
 * Coaching Insights table
 * Stores individual coaching insights generated by SAGE
 */
export const coachingInsights = pgTable("coaching_insights", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").notNull().references(() => coachingSessions.id),
  dimensionCode: text("dimension_code").notNull(), // "TECH", "TACT", "PHYS", "MENT", "CONS"
  insightType: text("insight_type").notNull(), // "strength", "weakness", "opportunity", "trend"
  title: text("title").notNull(),
  description: text("description").notNull(),
  priority: integer("priority").default(1).notNull(), // 1-5 with 5 being highest priority
  createdAt: timestamp("created_at").defaultNow().notNull(),
  isArchived: boolean("is_archived").default(false).notNull(),
  metadata: jsonb("metadata").default({}).notNull(),
});

/**
 * Training Plans table
 * Stores training plans generated by SAGE
 */
export const trainingPlans = pgTable("training_plans", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").notNull().references(() => coachingSessions.id),
  title: text("title").notNull(),
  description: text("description").notNull(),
  durationDays: integer("duration_days").notNull(),
  difficultyLevel: integer("difficulty_level").notNull(), // 1-5 scale
  focusAreas: text("focus_areas").notNull(), // Comma-separated dimension codes
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  status: text("status").notNull().default("active"), // "active", "completed", "archived"
  metadata: jsonb("metadata").default({}).notNull(),
});

/**
 * Training Exercises table
 * Stores exercises included in training plans
 */
export const trainingExercises = pgTable("training_exercises", {
  id: serial("id").primaryKey(),
  planId: integer("plan_id").notNull().references(() => trainingPlans.id),
  title: text("title").notNull(),
  description: text("description").notNull(),
  instructions: text("instructions").notNull(),
  durationMinutes: integer("duration_minutes").notNull(),
  dimensionCode: text("dimension_code").notNull(), // "TECH", "TACT", "PHYS", "MENT", "CONS"
  difficultyLevel: integer("difficulty_level").notNull(), // 1-5 scale
  equipmentNeeded: text("equipment_needed"),
  dayNumber: integer("day_number").notNull(), // Which day of the plan
  orderInDay: integer("order_in_day").notNull(), // Sequence within the day
  isCompleted: boolean("is_completed").default(false).notNull(),
  metadata: jsonb("metadata").default({}).notNull(),
});

/**
 * Coaching Content Library table
 * Stores pre-defined coaching content that can be used in insights and plans
 */
export const coachingContentLibrary = pgTable("coaching_content_library", {
  id: serial("id").primaryKey(),
  contentType: text("content_type").notNull(), // "insight", "exercise", "tip", "assessment"
  dimensionCode: text("dimension_code").notNull(), // "TECH", "TACT", "PHYS", "MENT", "CONS"
  title: text("title").notNull(),
  content: text("content").notNull(),
  skillLevel: text("skill_level").notNull(), // "beginner", "intermediate", "advanced"
  tags: text("tags").notNull(), // Comma-separated tags
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  metadata: jsonb("metadata").default({}).notNull(),
});

/**
 * User Progress Logs table
 * Tracks user progress through coaching sessions and exercises
 */
export const userProgressLogs = pgTable("user_progress_logs", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  sessionId: integer("session_id").references(() => coachingSessions.id),
  planId: integer("plan_id").references(() => trainingPlans.id),
  exerciseId: integer("exercise_id").references(() => trainingExercises.id),
  progressType: text("progress_type").notNull(), // "session_completed", "exercise_completed", "assessment"
  notes: text("notes"),
  rating: integer("rating"), // User rating 1-5
  createdAt: timestamp("created_at").defaultNow().notNull(),
  metadata: jsonb("metadata").default({}).notNull(),
});

// Define relationships between tables
export const coachingSessionsRelations = relations(coachingSessions, ({ one, many }) => ({
  user: one(users, {
    fields: [coachingSessions.userId],
    references: [users.id],
  }),
  insights: many(coachingInsights),
  trainingPlans: many(trainingPlans),
  progressLogs: many(userProgressLogs),
}));

export const coachingInsightsRelations = relations(coachingInsights, ({ one }) => ({
  session: one(coachingSessions, {
    fields: [coachingInsights.sessionId],
    references: [coachingSessions.id],
  }),
}));

export const trainingPlansRelations = relations(trainingPlans, ({ one, many }) => ({
  session: one(coachingSessions, {
    fields: [trainingPlans.sessionId],
    references: [coachingSessions.id],
  }),
  exercises: many(trainingExercises),
  progressLogs: many(userProgressLogs),
}));

export const trainingExercisesRelations = relations(trainingExercises, ({ one }) => ({
  plan: one(trainingPlans, {
    fields: [trainingExercises.planId],
    references: [trainingPlans.id],
  }),
}));

export const userProgressLogsRelations = relations(userProgressLogs, ({ one }) => ({
  user: one(users, {
    fields: [userProgressLogs.userId],
    references: [users.id],
  }),
  session: one(coachingSessions, {
    fields: [userProgressLogs.sessionId],
    references: [coachingSessions.id],
  }),
  plan: one(trainingPlans, {
    fields: [userProgressLogs.planId],
    references: [trainingPlans.id],
  }),
  exercise: one(trainingExercises, {
    fields: [userProgressLogs.exerciseId],
    references: [trainingExercises.id],
  }),
}));

// Create Zod schemas for insertion validation
export const insertCoachingSessionSchema = createInsertSchema(coachingSessions);
export const insertCoachingInsightSchema = createInsertSchema(coachingInsights);
export const insertTrainingPlanSchema = createInsertSchema(trainingPlans);
export const insertTrainingExerciseSchema = createInsertSchema(trainingExercises);
export const insertCoachingContentLibrarySchema = createInsertSchema(coachingContentLibrary);
export const insertUserProgressLogSchema = createInsertSchema(userProgressLogs);

// Export types
export type CoachingSession = typeof coachingSessions.$inferSelect;
export type InsertCoachingSession = typeof coachingSessions.$inferInsert;

export type CoachingInsight = typeof coachingInsights.$inferSelect;
export type InsertCoachingInsight = typeof coachingInsights.$inferInsert;

export type TrainingPlan = typeof trainingPlans.$inferSelect;
export type InsertTrainingPlan = typeof trainingPlans.$inferInsert;

export type TrainingExercise = typeof trainingExercises.$inferSelect;
export type InsertTrainingExercise = typeof trainingExercises.$inferInsert;

export type CoachingContentLibrary = typeof coachingContentLibrary.$inferSelect;
export type InsertCoachingContentLibrary = typeof coachingContentLibrary.$inferInsert;

export type UserProgressLog = typeof userProgressLogs.$inferSelect;
export type InsertUserProgressLog = typeof userProgressLogs.$inferInsert;

// Export dimension codes as a type for type safety
export const DimensionCodes = {
  TECH: "TECH", // Technical Skills
  TACT: "TACT", // Tactical Awareness
  PHYS: "PHYS", // Physical Fitness
  MENT: "MENT", // Mental Toughness
  CONS: "CONS", // Consistency
} as const;

export type DimensionCode = keyof typeof DimensionCodes;

// Export insight types as a type for type safety
export const InsightTypes = {
  strength: "strength",
  weakness: "weakness",
  opportunity: "opportunity",
  trend: "trend",
  recommendation: "recommendation",
} as const;

export type InsightType = keyof typeof InsightTypes;

// Export session types as a type for type safety
export const SessionTypes = {
  match_analysis: "match_analysis",
  assessment: "assessment",
  training_plan: "training_plan",
} as const;

export type SessionType = keyof typeof SessionTypes;