import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh-CN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries - Updated to include Mandarin (匹克球 = Pickleball)
const translations: Record<Language, Record<string, string>> = {
  'en': {
    // Navigation & Common
    'nav.dashboard': 'Dashboard',
    'nav.matches': 'Matches',
    'nav.communities': 'Communities',
    'nav.referrals': 'Referrals',
    'nav.tournaments': 'Tournaments',
    'nav.findCoaches': 'Find Coaches',
    'nav.findPlayers': 'Find Players',
    'nav.trainingFacilities': 'Training Facilities',
    'nav.logout': 'Logout',
    'common.loading': 'Getting ready...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.tryAgain': 'Please try again',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.playerPassport': 'Player Passport',
    'dashboard.passportCode': 'Passport Code',
    'dashboard.skillLevel': 'Skill Level',
    'dashboard.totalMatches': 'Total Matches',
    'dashboard.winRate': 'Win Rate',
    'dashboard.currentStreak': 'Current Streak',
    'dashboard.picklePoints': 'Pickle Points',
    'dashboard.recordMatch': 'Record Match',
    'dashboard.findCoaches': 'Find Coaches',
    'dashboard.findPlayers': 'Find Players',
    'dashboard.joinTournament': 'Join Tournament',
    'dashboard.becomeCoach': 'Become a Coach',
    'dashboard.manageCoachProfile': 'Manage Coach Profile',
    'dashboard.findTrainingFacilities': 'Find Training Facilities',
    
    // PCP Assessment
    'pcp.technicalSkills': 'Technical Skills',
    'pcp.tacticalSkills': 'Tactical Skills',
    'pcp.physicalFitness': 'Physical Fitness',
    'pcp.mentalSkills': 'Mental Skills',
    'pcp.overallRating': 'Overall PCP Rating',
    'pcp.assessment': 'PCP Assessment',
    'pcp.coachingCertification': 'PCP Coaching Certification Programme',
    
    // Coaching
    'coach.findYourPerfectCoach': 'Find Your Perfect Coach',
    'coach.connectWithExperts': 'Connect with expert coaches who will transform your skills and elevate your performance on the court',
    'coach.filterBySpecialty': 'Filter by Specialty',
    'coach.allCoaches': 'All Coaches',
    'coach.experienceYears': 'years experience',
    'coach.hourlyRate': 'per hour',
    'coach.bookSession': 'Book Session',
    'coach.verified': 'Verified',
    'coach.specialties': 'Specialties',
    'coach.certifications': 'Certifications',
    'coach.rating': 'Rating',
    'coach.reviews': 'reviews',
    
    // Coming Soon
    'comingSoon.feature': 'Feature Coming Soon',
    'comingSoon.tournamentRegistration': 'Tournament Registration',
    'comingSoon.tournamentDescription': 'Our tournament discovery and registration system is launching soon! You\'ll be able to browse upcoming tournaments, register with one click, and track your tournament history.',
    'comingSoon.playerDiscovery': 'Player Discovery',
    'comingSoon.playerDescription': 'The player finder feature is coming soon! Connect with players in your area, find practice partners, and organize friendly matches based on skill level and availability.',
    'comingSoon.trainingFacilities': 'Training Facilities',
    'comingSoon.facilitiesDescription': 'Our training facility discovery system is launching soon! You\'ll be able to find nearby training centers, view their amenities, and book courts and classes directly through the platform.',
    
    // Dashboard QR & Photo
    'dashboard.qr.codeHidden': 'Code Hidden',
    'dashboard.qr.codeRevealed': 'Code Revealed',
    'dashboard.qr.codeHiddenDesc': 'Your passport code is now hidden',
    'dashboard.qr.yourCode': 'Your passport code',
    'dashboard.tournaments.title': 'Tournament Registration',
    'dashboard.tournaments.comingSoon': 'Our tournament discovery and registration system is launching soon! You\'ll be able to browse upcoming tournaments, register with one click, and track your tournament history.',
    'dashboard.players.title': 'Player Discovery',
    'dashboard.players.comingSoon': 'The player finder feature is coming soon! Connect with players in your area, find practice partners, and organize friendly matches based on skill level and availability.',
    'dashboard.training.title': 'Training Facilities',
    'dashboard.training.comingSoon': 'Our training facility discovery system is launching soon! You\'ll be able to find nearby training centers, view their amenities, and book courts and classes directly through the platform.',
    'dashboard.photo.updated': 'Profile Photo Updated',
    'dashboard.photo.uploadedSuccess': 'Your new profile photo has been uploaded successfully.',
    'dashboard.photo.update': 'Update Photo',
    'dashboard.passport.codeCopied': 'Passport Code Copied!',
    'dashboard.passport.copiedToClipboard': 'copied to clipboard',
    'dashboard.rankings.title': 'PCP Global Ranking System',
    'dashboard.rankings.ranked': 'Ranked',
    'dashboard.rankings.unranked': 'Unranked',
    'dashboard.rankings.rank': 'Rank',
    'dashboard.rankings.matches': 'matches',
    'dashboard.rankings.need': 'Need',
    'dashboard.rankings.more': 'more',
    'dashboard.qr.codeVisible': 'Code Visible',
    'dashboard.qr.tapToReveal': 'Tap to Reveal Code',
    'dashboard.qr.shareCode': 'Share this code with other players',
    'dashboard.qr.scanDescription': 'Players scan to initiate matches or view stats',
    'dashboard.cards.picklePoints': 'Pickle Points',
    'dashboard.cards.currentRank': 'Current Rank',
    'dashboard.cards.matches': 'Matches',
    'dashboard.cards.winRate': 'Win Rate',
    'dashboard.cards.skillLevel': 'Skill Level',
    'dashboard.cards.duprRating': 'DUPR Rating',
    'dashboard.form.editProfile': 'Edit Profile Details',
    'dashboard.form.basicInfo': 'Basic Information',
    'dashboard.form.displayName': 'Display Name',
    'dashboard.form.firstName': 'First Name',
    'dashboard.form.lastName': 'Last Name',
    'dashboard.form.location': 'Location',
    'dashboard.form.bio': 'Bio',
    'dashboard.passport.title': 'Player Passport',
    'dashboard.stats.rankingPoints': 'Ranking Points',
    'dashboard.stats.streak': 'Streak',
    'dashboard.stats.passportCode': 'Passport Code',
    'dashboard.stats.tapToCopy': 'Tap to copy',
    'dashboard.rankings.noData': 'No ranking data available',
    'dashboard.rankings.playMatches': 'Play matches to start building your rankings',
    'dashboard.rankings.systemVersion': 'PCP Global Ranking System v2.0 (Multi-Division)',
    'dashboard.rankings.eligibleCategories': 'eligible categories',
    'dashboard.form.selectPaddleBrand': 'Select paddle brand',
    'dashboard.form.paddleModel': 'Paddle Model',
    'dashboard.form.coachBio': 'Coach Bio',
    'dashboard.form.coachBioPlaceholder': 'Describe your coaching philosophy and experience...',
    'dashboard.form.experienceYears': 'Experience Years',
    'dashboard.form.hourlyRate': 'Hourly Rate ($)',
    'dashboard.form.specialties': 'Specialties',
    'dashboard.form.specialtiesPlaceholder': 'e.g., Beginner Training, Tournament Prep, Technical Analysis',
    'dashboard.form.certifications': 'Certifications',
    'dashboard.form.certificationsPlaceholder': 'e.g., PPR Certified, Level 3 Instructor, USA Pickleball Certified',
    'dashboard.form.externalRatings': 'External Ratings',
    'dashboard.form.duprRating': 'DUPR Rating',
    'dashboard.form.usaPickleballId': 'USA Pickleball ID',
    'dashboard.form.ifpRating': 'IFP Rating',
    'dashboard.form.iptpaRating': 'IPTPA Rating',
    'dashboard.form.physicalInfo': 'Physical Information',
    'dashboard.form.height': 'Height (cm)',
    'dashboard.form.reach': 'Reach (cm)',
    'dashboard.form.yearOfBirth': 'Year of Birth',
    'dashboard.form.gender': 'Gender',
    'dashboard.form.selectGender': 'Select Gender',
    'dashboard.form.male': 'Male',
    'dashboard.form.female': 'Female',
    'dashboard.form.other': 'Other',
    'dashboard.form.preferNotToSay': 'Prefer not to say',
    'dashboard.form.cancel': 'Cancel',
    'dashboard.form.saveChanges': 'Save Changes',
    'dashboard.form.saving': 'Saving...',

    // Pickle Points
    'dashboard.picklePoints.title': 'Your Digital Pickleball Currency',
    'dashboard.picklePoints.description': 'Pickle Points are rewards you earn for being active in the pickleball community. Play matches, complete your profile, participate in tournaments, and engage with other players to earn points.',
    'dashboard.picklePoints.winMatches': 'Win Matches',
    'dashboard.picklePoints.winMatchesPoints': '+15-25 pts',
    'dashboard.picklePoints.profileUpdates': 'Profile Updates',
    'dashboard.picklePoints.profileUpdatesPoints': '+5-10 pts',
    'dashboard.picklePoints.joinTournaments': 'Join Tournaments',
    'dashboard.picklePoints.joinTournamentsPoints': '+20-50 pts',
    'dashboard.picklePoints.dailyActivity': 'Daily Activity',
    'dashboard.picklePoints.dailyActivityPoints': '+3-8 pts',
    'dashboard.picklePoints.redeemTitle': 'Redeem for Rewards',
    'dashboard.picklePoints.redeemDescription': 'Use your points for exclusive rewards from our partner merchants:',
    'dashboard.picklePoints.redeemCourt': 'Court time discounts',
    'dashboard.picklePoints.redeemEquipment': 'Equipment and gear',
    'dashboard.picklePoints.redeemTournament': 'Tournament entry fees',
    'dashboard.picklePoints.redeemCoaching': 'Coaching sessions',
    'dashboard.picklePoints.redeemEvents': 'Special events access',
    'dashboard.picklePoints.disclaimer': 'Points are earned through verified activities and cannot be transferred between accounts.',
    'dashboard.picklePoints.totalPoints': 'Total Points',
    'dashboard.picklePoints.matchWins': 'Match Wins',
    'dashboard.picklePoints.participation': 'Participation',
    'dashboard.picklePoints.profileBonus': 'Profile Bonus',
    'dashboard.picklePoints.system': 'System',
    'dashboard.picklePoints.hybrid': 'Hybrid',
    'dashboard.picklePoints.spendPoints': 'Spend Points',
    'dashboard.picklePoints.spendDescription': 'Redeem your Pickle Points for exclusive rewards, merchandise, and tournament entry fees.',
    'dashboard.picklePoints.earnMore': 'Earn More',
    'dashboard.picklePoints.earnDescription': 'Discover new ways to earn Pickle Points through challenges, referrals, and community activities.',
    'dashboard.picklePoints.dialogTitle': 'What are Pickle Points?',

    // Profile Completion Modal
    'profile.completion.title': 'Complete Your Profile',
    'profile.completion.description': 'Help other players recognize you by adding your first and last name. Currently showing as "{username}" in match history.',
    'profile.completion.firstName': 'First Name',
    'profile.completion.lastName': 'Last Name',
    'profile.completion.firstNamePlaceholder': 'Enter your first name',
    'profile.completion.lastNamePlaceholder': 'Enter your last name',
    'profile.completion.skipForNow': 'Skip for Now',
    'profile.completion.updating': 'Updating...',
    'profile.completion.updateProfile': 'Update Profile',

    // Navigation Items
    'nav.features': 'Features',
    'nav.pcpCertification': 'PCP Certification',
    'nav.developmentHub': 'Development Hub',
    'nav.adminPanel': 'Admin Panel',
    'nav.home': 'Home',
    'nav.community': 'Community',
    'nav.coaching': 'Coaching',
    'nav.profile': 'Profile',

    // Match Recording Forms
    'match.form.matchResult': 'Match Result',
    'match.form.selectResult': 'Select result',
    'match.form.win': 'Win',
    'match.form.loss': 'Loss',
    'match.form.score': 'Score (Optional)',
    'match.form.scoreOptional': 'Score (Optional)',
    'match.form.scorePlaceholder': 'e.g., 11-9, 11-7 or 11-5, 8-11, 11-3',
    'match.form.notes': 'Notes (Optional)',
    'match.form.notesPlaceholder': 'Add any notes about the match...',
    'match.form.format': 'Format',
    'match.form.selectFormat': 'Select format',
    'match.form.mensSingles': 'Men\'s Singles',
    'match.form.womensSingles': 'Women\'s Singles',
    'match.form.mensDoubles': 'Men\'s Doubles',
    'match.form.womensDoubles': 'Women\'s Doubles',
    'match.form.mixedDoubles': 'Mixed Doubles',
    'match.form.division': 'Division',
    'match.form.selectDivision': 'Select division',
    'match.form.pro': 'Pro',
    'match.form.open': 'Open/19+',
    'match.form.tournament': 'Tournament',
    'match.form.selectTournament': 'Select tournament',
    'match.form.matchType': 'Match Type',
    'match.form.casual': 'Casual',
    'match.form.league': 'League',
    'match.form.tournamentType': 'Tournament',
    'match.form.exhibition': 'Exhibition',
    'match.form.tournamentTier': 'Tournament Tier',
    'match.form.selectTournamentTier': 'Select tournament tier',
    'match.form.club': 'Club',
    'match.form.regional': 'Regional',
    'match.form.recordedSuccessfully': 'Match Recorded Successfully',
    'match.form.earnedPoints': 'Earned {{points}} ranking points and {{xp}} XP',
    'match.form.failedToRecord': 'Failed to Record Match',
    'match.form.noOpponentSelected': 'No Opponent Selected',
    'match.form.selectOpponent': 'Please select an opponent to record the match',
    'match.form.recordCasualMatch': 'Record Casual Match',
    'match.form.recordCasualDescription': 'Record matches with the hybrid ranking system. Tournament points count 100%, casual matches 50%.',

    // Dashboard Tabs
    'dashboard.tabs.performance': 'Performance',
    'dashboard.tabs.recentMatches': 'Recent Matches',
    'dashboard.tabs.achievements': 'Achievements',
    'dashboard.tabs.community': 'Community',

    // Performance Trends
    'dashboard.performance.title': 'Performance Trends',
    'dashboard.performance.overallRating': 'Overall Rating',
    'dashboard.performance.passportCode': 'Passport Code',
    'dashboard.performance.notSet': 'Not Set',
    'dashboard.performance.hide': 'Hide',
    'dashboard.performance.show': 'Show',
    'dashboard.performance.recentForm': 'Recent Form',
    'dashboard.performance.improving': 'Improving',
    'dashboard.performance.pointsThisMonth': 'Points This Month',

    // Quick Actions
    'dashboard.quickActions.title': 'Quick Actions',
    'dashboard.quickActions.recordMatch': 'Record New Match',
    'dashboard.quickActions.manageCoachProfile': 'Manage Coach Profile',
    'dashboard.quickActions.becomeCoach': 'Become a Coach',
    'dashboard.quickActions.findTrainingFacilities': 'Find Training Facilities',
    'dashboard.quickActions.findCoaches': 'Find Coaches',
    'dashboard.quickActions.joinTournament': 'Join Tournament',
    'dashboard.quickActions.findPlayers': 'Find Players',

    // Landing Page
    'landing.brand': 'Pickle+',
    'landing.nav.features': 'Features',
    'landing.nav.benefits': 'Benefits',
    'landing.nav.community': 'Community',
    'landing.nav.dashboard': 'Dashboard',
    'landing.nav.getStarted': 'Get Started',
    'landing.hero.badge': 'New Platform Available',
    'landing.hero.title': 'One Passport.',
    'landing.hero.titleHighlight': 'Every Court.',
    'landing.hero.titleEnd': 'Your True Ranking.',
    'landing.hero.subtitle1': 'The first transparent ranking system built for players, by players.',
    'landing.hero.subtitle2': 'No black boxes. No hidden algorithms.',
    'landing.hero.getStarted': 'Start Your Player Journey',
    'landing.hero.achievementBadge': '100% Platform Capability Achieved',
    'landing.hero.seeRanking': 'See How Ranking Works',

    // Ranking Section
    'landing.ranking.title': 'Fair. Transparent. Proven.',
    'landing.ranking.subtitle': 'Age-adjusted rankings that actually make sense. Built with sophisticated algorithms that reward skill over demographics.',

    // Tier System
    'landing.tiers.recreational': 'Recreational',
    'landing.tiers.recreationalPoints': '0-299 pts',
    'landing.tiers.competitive': 'Competitive',
    'landing.tiers.competitivePoints': '300-999 pts',
    'landing.tiers.elite': 'Elite',
    'landing.tiers.elitePoints': '1000-1799 pts',
    'landing.tiers.professional': 'Professional',
    'landing.tiers.professionalPoints': '1800+ pts',

    // Philosophy Section
    'landing.philosophy.title': 'Our Ranking Philosophy',
    'landing.philosophy.subtitle': 'Every player deserves a fair shot. Our algorithm recognizes that skill transcends age, gender, and playing frequency.',

    // Features
    'landing.features.performanceTitle': 'Performance Weighted',
    'landing.features.performanceDesc': 'Tournament victories carry more weight than casual games, reflecting competitive achievement.',
    'landing.features.ageTitle': 'Age Balanced',
    'landing.features.ageDesc': 'Thoughtful adjustments ensure players of all ages can compete meaningfully within their cohort.',
    'landing.features.activityTitle': 'Activity Protected',
    'landing.features.activityDesc': 'Smart decay systems maintain your ranking even during busy life periods.',

    // Result Section
    'landing.result.title': 'The Result: True Competitive Balance',
    'landing.result.description': 'A 25-year-old college athlete and a 55-year-old weekend warrior both earn rankings that reflect their skill within their respective competitive contexts.',

    // Additional Features
    'landing.features.ageGroupTitle': 'Age Group Fairness',
    'landing.features.ageGroupDesc': 'Automatic age multipliers ensure fair competition across generations with proven mathematical balance.',
    'landing.features.genderTitle': 'Gender Balance System',
    'landing.features.genderDesc': 'Cross-gender bonus system for developing players, with elite-level competitive parity.',
    'landing.features.decayTitle': 'Decay Protection',
    'landing.features.decayDesc': 'Tier-specific activity requirements with enhanced professional weighting system.',

    // Passport Section
    'landing.passport.title1': 'Your Digital',
    'landing.passport.title2': 'Player Passport',
    'landing.passport.subtitle': 'From 0% to Champion Status. Track your journey with meaningful milestones, Pickle Points rewards, and complete profile progression.',
    'landing.passport.feature1': 'QR Code court check-ins',
    'landing.passport.feature2': 'Real-time ranking updates',
    'landing.passport.feature3': 'Milestone reward system',
    'landing.passport.feature4': 'Cross-platform compatibility',
    'landing.passport.createButton': 'Create Your Passport',
    'landing.passport.learnMore': 'Learn More About Rankings',

    // Community Section
    'landing.community.title': 'Built by the Community',
    'landing.community.subtitle': 'Developed with input from players, coaches, and tournament directors to create the ranking system pickleball deserves.',
    'landing.community.stat1': 'Platform Ready',
    'landing.community.stat2': 'Classification System',
    'landing.community.stat3': 'Age & Gender Balance',
    'landing.community.joinButton': 'Join the Revolution',

    // Footer
    'landing.footer.copyright': '© 2025 Pickle+. The future of pickleball ranking systems.',
    'landing.hero.description': 'Join thousands of players using advanced analytics, coaching tools, and community features to elevate their pickleball performance.',
    'landing.hero.startFree': 'Start Free Today',
    'landing.hero.watchDemo': 'Watch Demo',
    'landing.hero.goToDashboard': 'Go to Dashboard',
    'landing.hero.feature1': 'Free Forever',
    'landing.hero.feature2': 'Setup in 2 minutes',
    'landing.sport': 'pickleball',
    'landing.hero.card.title': 'Player Stats',
    'landing.hero.card.rating': 'DUPR Rating',
    'landing.hero.card.matches': 'Matches',
    'landing.hero.card.rank': 'Local Rank',
    'landing.hero.card.points': 'Points',
    'landing.features.title': 'Everything You Need to Excel',
    'landing.features.description': 'Comprehensive tools designed to help players at every level improve their game and connect with the community.',
    'landing.features.analytics.title': 'Smart Analytics',
    'landing.features.analytics.description': 'Track performance metrics, analyze game patterns, and get personalized insights to improve your gameplay.',
    'landing.features.community.title': 'Vibrant Community',
    'landing.features.community.description': 'Connect with players worldwide, find practice partners, and join local tournaments and events.',
    'landing.features.tournaments.title': 'Tournament Management',
    'landing.features.tournaments.description': 'Organize, join, and track tournaments with our comprehensive tournament management system.',
    'landing.features.coaching.title': 'Expert Coaching',
    'landing.features.coaching.description': 'Access certified coaches, get personalized training plans, and track your skill development progress.',
    'landing.features.mobile.title': 'Mobile Ready',
    'landing.features.mobile.description': 'Full-featured mobile app to track matches, view stats, and stay connected with your community anywhere.',
    'landing.features.progress.title': 'Progress Tracking',
    'landing.features.progress.description': 'Monitor your improvement over time with detailed analytics and achievement systems.',
    'landing.benefits.title': 'Why Players Choose Pickle+',
    'landing.benefits.description': 'Our platform combines cutting-edge technology with community-driven features to create the ultimate pickleball experience.',
    'landing.benefits.benefit1.title': 'Data-Driven Improvement',
    'landing.benefits.benefit1.description': 'Make informed decisions about your training with comprehensive performance analytics.',
    'landing.benefits.benefit2.title': 'Global Community Access',
    'landing.benefits.benefit2.description': 'Connect with players worldwide and participate in events that match your skill level.',
    'landing.benefits.benefit3.title': 'Professional Growth',
    'landing.benefits.benefit3.description': 'Access coaching certification programs and develop your skills as a player or instructor.',
    'landing.benefits.stats.title': 'Platform Impact',
    'landing.benefits.stats.improvement': 'Player Improvement',
    'landing.benefits.stats.players': 'Active Players',
    'landing.benefits.stats.setup': 'Quick Setup',
    'landing.benefits.stats.tracking': 'Match Tracking',
    // Removed duplicate - keeping the original above
    'landing.community.description': 'Connect with passionate pickleball players from around the world who are transforming their game with data-driven insights.',
    'landing.community.countries': 'Countries Represented',
    'landing.community.activeUsers': 'Active Users',
    'landing.community.matchesTracked': 'Matches Tracked',
    'landing.community.joinNow': 'Join the Community',
    'landing.community.goToDashboard': 'Go to Dashboard',
    'landing.footer.description': 'The comprehensive platform for pickleball players to track, improve, and connect.',
    'landing.footer.product': 'Product',
    'landing.footer.features': 'Features',
    'landing.footer.pricing': 'Pricing',
    'landing.footer.tutorials': 'Tutorials',
    'landing.footer.company': 'Company',
    'landing.footer.about': 'About',
    'landing.footer.contact': 'Contact',
    'landing.footer.privacy': 'Privacy',
    'landing.footer.support': 'Support',
    'landing.footer.help': 'Help Center',
    'landing.footer.community': 'Community',
    'landing.footer.updates': 'Updates',
    'landing.footer.rights': 'All rights reserved.',
    
    // Authentication
    'auth.backToHome': 'Back to Home',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createPassport': 'Create Your Passport',
    'auth.signInDescription': 'Sign in to access your player dashboard',
    'auth.joinRevolution': 'Join the transparent ranking revolution',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.usernameOrEmail': 'Username or Email',
    'auth.usernamePlaceholder': 'Enter your username or email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.rememberMe': 'Remember me for 30 days',
    'auth.loggingIn': 'Signing In...',
    'auth.signInToDashboard': 'Sign In to Dashboard',
    'auth.firstName': 'First Name',
    'auth.firstNamePlaceholder': 'John',
    'auth.lastName': 'Last Name',
    'auth.lastNamePlaceholder': 'Doe',
    'auth.username': 'Username',
    'auth.usernamePlaceholderRegister': 'Choose a unique username',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.createPassword': 'Create a strong password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.birthYear': 'Birth Year',
    'auth.birthYearPlaceholder': '1990',
    'auth.skillLevel': 'Skill Level',
    'auth.selectLevel': 'Select level',
    'auth.beginner': 'Beginner',
    'auth.intermediate': 'Intermediate',
    'auth.advanced': 'Advanced',
    'auth.expert': 'Expert',
    'auth.location': 'Location (Optional)',
    'auth.locationPlaceholder': 'City, State/Country',
    'auth.agreeToTerms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.creatingAccount': 'Creating Account...',
    'auth.createPassportButton': 'Create My Player Passport',
    'auth.signingIn': 'Signing you in...',
    'auth.creatingPassport': 'Creating your player passport...',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    
    // Profile & Player Info
    'profile.personalInfo': 'Personal Information',
    'profile.statistics': 'Statistics',
    'profile.equipment': 'Equipment',
    'profile.preferences': 'Preferences',
    'profile.achievements': 'Achievements',
    'profile.updatePhoto': 'Update Photo',
    'profile.height': 'Height',
    'profile.weight': 'Weight',
    'profile.dominantHand': 'Dominant Hand',
    'profile.playingStyle': 'Playing Style',
    
    // Dashboard Stats
    'stats.duprRating': 'DUPR Rating',
    'stats.winRate': 'Win Rate',
    'stats.matches': 'Matches',
    'stats.loading': 'Loading...',
    
    // Tournament & Competition
    'tournament.upcoming': 'Upcoming Tournaments',
    'tournament.results': 'Tournament Results',
    'tournament.registration': 'Registration',
    'tournament.bracket': 'Bracket',
    'tournament.leaderboard': 'Leaderboard',
    'tournament.format': 'Format',
    'tournament.division': 'Division',
    'tournament.date': 'Date',
    'tournament.location': 'Location',
    'tournament.today': 'Today!',
    'tournament.daysRemaining': '{count} days remaining',
    'tournament.players': 'Players',
    'tournament.checkedIn': 'Checked In',
    'tournament.checkInRequired': 'Check-in Required Soon',
    'tournament.registrationComplete': 'Registration Complete',
    
    // Training & Facilities
    'training.centers': 'Training Centers',
    'training.schedule': 'Class Schedule',
    'training.bookClass': 'Book Class',
    'training.history': 'Training History',
    'training.instructor': 'Instructor',
    'training.duration': 'Duration',
    'training.capacity': 'Capacity',
    'training.available': 'Available',
    'training.full': 'Full',
    
    // Match Recording
    'match.record': 'Record Match',
    'match.opponent': 'Opponent',
    'match.score': 'Score',
    'match.result': 'Result',
    'match.win': 'Win',
    'match.loss': 'Loss',
    'match.date': 'Date',
    'match.format': 'Format',
    'match.singles': 'Singles',
    'match.doubles': 'Doubles',
    'match.mixed': 'Mixed Doubles',
    
    // Time & Status
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This Week',
    'time.thisMonth': 'This Month',
    'time.allTime': 'All Time',
    'status.online': 'Online',
    'status.offline': 'Offline',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.available': 'Available',
    'status.busy': 'Busy',
    
    // Equipment & Gear
    'equipment.paddle': 'Paddle',
    'equipment.shoes': 'Shoes',
    'equipment.apparel': 'Apparel',
    'equipment.accessories': 'Accessories',
    'equipment.brand': 'Brand',
    'equipment.model': 'Model',
    'equipment.primary': 'Primary',
    'equipment.backup': 'Backup',
    
    // Notifications & Messages
    'notification.success': 'Success',
    'notification.error': 'Error',
    'notification.warning': 'Warning',
    'notification.info': 'Info',
    'notification.copied': 'Copied',
    'notification.saved': 'Saved',
    'notification.updated': 'Updated',
    'notification.deleted': 'Deleted',
    
    // Actions & Buttons
    'action.view': 'View',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.add': 'Add',
    'action.remove': 'Remove',
    'action.update': 'Update',
    'action.refresh': 'Refresh',
    'action.search': 'Search',
    'action.filter': 'Filter',
    'action.sort': 'Sort',
    'action.export': 'Export',
    'action.import': 'Import',
    
    // Settings & Configuration
    'settings.general': 'General',
    'settings.privacy': 'Privacy',
    'settings.notifications': 'Notifications',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.account': 'Account',
    'settings.security': 'Security',
    'settings.preferences': 'Preferences',
    
    // Coaching
    'coaching.pcpProgramme': 'Coaching Bio',
    
    // Authentication
    'auth.backToHome': 'Back to Home',
    'auth.welcomeTitle': 'Welcome to Pickle+',
    'auth.welcomeSubtitle': 'Join the fastest growing pickleball community',
    'auth.loginTab': 'Login',
    'auth.registerTab': 'Register',
    'auth.signInTitle': 'Sign in to your account',
    'auth.signInDescription': 'Enter your credentials to access your Pickle+ account.',
    'auth.usernameOrEmail': 'Username or Email',
    'auth.usernamePlaceholder': 'Enter your username or email',
    'auth.authPassword': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.rememberMe': 'Remember me',
    'auth.loggingIn': 'Logging in...',
    'auth.createAccountTitle': 'Create your account',
    'auth.createAccountDescription': 'Join thousands of players and elevate your pickleball journey.',
    'auth.authFirstName': 'First Name',
    'auth.firstNamePlaceholder': 'Enter your first name',
    'auth.authLastName': 'Last Name',
    'auth.lastNamePlaceholder': 'Enter your last name',
    'auth.authUsername': 'Username',
    'auth.authUsernamePlaceholder': 'Choose a username',
    'auth.authEmail': 'Email',
    'auth.emailPlaceholder': 'Enter your email address',
    'auth.authConfirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.createAccount': 'Create Account',
    'auth.creatingAccount': 'Creating Account...'
  },
  'zh-CN': {
    // Navigation & Common
    'nav.dashboard': '控制台',
    'nav.matches': '比赛',
    'nav.communities': '社区',
    'nav.referrals': '推荐',
    'nav.tournaments': '锦标赛',
    'nav.findCoaches': '寻找教练',
    'nav.findPlayers': '寻找球员',
    'nav.trainingFacilities': '训练设施',
    'nav.logout': '登出',
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.confirm': '确认',
    'common.back': '返回',
    'common.next': '下一步',
    'common.submit': '提交',
    'common.close': '关闭',
    'common.tryAgain': '请重试',
    
    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.playerPassport': '球员护照',
    'dashboard.passportCode': '护照代码',
    'dashboard.skillLevel': '技能等级',
    'dashboard.totalMatches': '总比赛数',
    'dashboard.winRate': '胜率',
    'dashboard.currentStreak': '当前连胜',
    'dashboard.picklePoints': '泡菜积分',
    'dashboard.recordMatch': '记录比赛',
    'dashboard.findCoaches': '寻找教练',
    'dashboard.findPlayers': '寻找球员',
    'dashboard.joinTournament': '参加锦标赛',
    'dashboard.becomeCoach': '成为教练',
    'dashboard.manageCoachProfile': '管理教练资料',
    'dashboard.findTrainingFacilities': '寻找训练设施',
    
    // PCP Assessment
    'pcp.technicalSkills': '技术技能',
    'pcp.tacticalSkills': '战术技能',
    'pcp.physicalFitness': '体能',
    'pcp.mentalSkills': '心理技能',
    'pcp.overallRating': '总体PCP评级',
    'pcp.assessment': 'PCP评估',
    'pcp.coachingCertification': 'PCP教练认证计划',
    
    // Coaching
    'coach.findYourPerfectCoach': '寻找您的完美教练',
    'coach.connectWithExperts': '与专业教练联系，他们将改变您的技能并提升您在球场上的表现',
    'coach.filterBySpecialty': '按专业筛选',
    'coach.allCoaches': '所有教练',
    'coach.experienceYears': '年经验',
    'coach.hourlyRate': '每小时',
    'coach.bookSession': '预约课程',
    'coach.verified': '已验证',
    'coach.specialties': '专业',
    'coach.certifications': '认证',
    'coach.rating': '评级',
    'coach.reviews': '评论',
    
    // Coming Soon
    'comingSoon.feature': '功能即将推出',
    'comingSoon.tournamentRegistration': '锦标赛报名',
    'comingSoon.tournamentDescription': '我们的锦标赛发现和报名系统即将推出！您将能够浏览即将到来的锦标赛，一键报名，并跟踪您的锦标赛历史。',
    'comingSoon.playerDiscovery': '球员发现',
    'comingSoon.playerDescription': '球员查找功能即将推出！与您所在地区的球员联系，寻找练习伙伴，并根据技能水平和可用性组织友谊赛。',
    'comingSoon.trainingFacilities': '训练设施',
    'comingSoon.facilitiesDescription': '我们的训练设施发现系统即将推出！您将能够找到附近的训练中心，查看其设施，并直接通过平台预订球场和课程。',

    // Match Recording Forms
    'match.form.matchResult': '比赛结果',
    'match.form.selectResult': '选择结果',
    'match.form.win': '胜利',
    'match.form.loss': '失败',
    'match.form.score': '比分（可选）',
    'match.form.scoreOptional': '比分（可选）',
    'match.form.scorePlaceholder': '例如：11-9, 11-7 或 11-5, 8-11, 11-3',
    'match.form.notes': '备注（可选）',
    'match.form.notesPlaceholder': '添加关于比赛的任何备注...',
    'match.form.format': '比赛形式',
    'match.form.selectFormat': '选择比赛形式',
    'match.form.mensSingles': '男子单打',
    'match.form.womensSingles': '女子单打',
    'match.form.mensDoubles': '男子双打',
    'match.form.womensDoubles': '女子双打',
    'match.form.mixedDoubles': '混合双打',
    'match.form.division': '组别',
    'match.form.selectDivision': '选择组别',
    'match.form.pro': '职业组',
    'match.form.open': '公开组/19+',
    'match.form.tournament': '锦标赛',
    'match.form.selectTournament': '选择锦标赛',
    'match.form.matchType': '比赛类型',
    'match.form.casual': '休闲',
    'match.form.league': '联赛',
    'match.form.tournamentType': '锦标赛',
    'match.form.exhibition': '表演赛',
    'match.form.tournamentTier': '锦标赛等级',
    'match.form.selectTournamentTier': '选择锦标赛等级',
    'match.form.club': '俱乐部',
    'match.form.regional': '地区',
    'match.form.recordedSuccessfully': '比赛记录成功',
    'match.form.earnedPoints': '获得{{points}}排名积分和{{xp}}经验值',
    'match.form.failedToRecord': '记录比赛失败',
    'match.form.noOpponentSelected': '未选择对手',
    'match.form.selectOpponent': '请选择对手以记录比赛',
    'match.form.recordCasualMatch': '记录休闲比赛',
    'match.form.recordCasualDescription': '使用混合排名系统记录比赛。锦标赛积分计100%，休闲比赛计50%。',
    
    // Tournament Components
    'tournament.registrationStatus': '报名状态',
    'tournament.checkedIn': '已签到',
    'tournament.confirmed': '已确认',
    'tournament.division': '组别',
    'tournament.notSpecified': '未指定',
    'tournament.joinExciting': '参加这个精彩的比赛！',
    'tournament.viewDetails': '查看详情',
    'tournament.registerNow': '立即报名',
    'tournament.upcoming': '即将开始',
    'tournament.inProgress': '进行中',
    'tournament.completed': '已完成',
    'tournament.cancelled': '已取消',
    'tournament.active': '活跃',
    'tournament.inactive': '不活跃',
    'tournament.format': '赛制',
    'tournament.category': '类别',
    'tournament.participants': '参与者',
    'tournament.teams': '队伍',
    'tournament.players': '球员',
    'tournament.venue': '场地',
    'tournament.manage': '管理',
    'tournament.delete': '删除',
    'tournament.deleteTournament': '删除比赛',
    'tournament.deleteConfirm': '您确定要删除"{{name}}"吗？此操作无法撤销。',
    'tournament.cancel': '取消',
    'tournament.noDescription': '无描述',
    'tournament.daysRemaining': '还有{{days}}天',
    'tournament.today': '今天！',
    'tournament.checkInRequired': '即将需要签到',
    'tournament.registrationComplete': '报名完成',
    'tournament.singleElimination': '单淘汰赛',
    'tournament.doubleElimination': '双淘汰赛',
    'tournament.roundRobin': '循环赛',
    'tournament.roundRobinToBracket': '循环赛转淘汰赛',
    'tournament.tier.club': '俱乐部',
    'tournament.tier.district': '地区',
    'tournament.tier.city': '城市',
    'tournament.tier.provincial': '省级',
    'tournament.tier.national': '国家级',
    'tournament.tier.regional': '区域',
    'tournament.tier.international': '国际',
    
    // Dashboard QR & Photo
    'dashboard.qr.codeHidden': '代码已隐藏',
    'dashboard.qr.codeRevealed': '代码已显示',
    'dashboard.qr.codeHiddenDesc': '您的护照代码现已隐藏',
    'dashboard.qr.yourCode': '您的护照代码',
    'dashboard.tournaments.title': '锦标赛报名',
    'dashboard.tournaments.comingSoon': '我们的锦标赛发现和报名系统即将推出！您将能够浏览即将到来的锦标赛，一键报名，并跟踪您的锦标赛历史。',
    'dashboard.players.title': '球员发现',
    'dashboard.players.comingSoon': '球员查找功能即将推出！与您所在地区的球员联系，寻找练习伙伴，并根据技能水平和可用性组织友谊赛。',
    'dashboard.training.title': '训练设施',
    'dashboard.training.comingSoon': '我们的训练设施发现系统即将推出！您将能够找到附近的训练中心，查看其设施，并直接通过平台预订球场和课程。',
    'dashboard.photo.updated': '个人资料照片已更新',
    'dashboard.photo.uploadedSuccess': '您的新个人资料照片已成功上传。',
    'dashboard.photo.update': '更新照片',
    'dashboard.passport.codeCopied': '护照代码已复制！',
    'dashboard.passport.copiedToClipboard': '已复制到剪贴板',
    'dashboard.rankings.title': 'PCP全球排名系统',
    'dashboard.rankings.ranked': '已排名',
    'dashboard.rankings.unranked': '未排名',
    'dashboard.rankings.rank': '排名',
    'dashboard.rankings.matches': '比赛',
    'dashboard.rankings.need': '需要',
    'dashboard.rankings.more': '更多',
    'dashboard.qr.codeVisible': '代码可见',
    'dashboard.qr.tapToReveal': '点击显示代码',
    'dashboard.qr.shareCode': '与其他球员分享此代码',
    'dashboard.qr.scanDescription': '球员扫描以发起比赛或查看统计数据',
    'dashboard.cards.picklePoints': 'Pickle积分',
    'dashboard.cards.currentRank': '当前排名',
    'dashboard.cards.matches': '比赛',
    'dashboard.cards.winRate': '胜率',
    'dashboard.cards.skillLevel': '技能水平',
    'dashboard.cards.duprRating': 'DUPR评级',
    'dashboard.form.editProfile': '编辑个人资料详情',
    'dashboard.form.basicInfo': '基本信息',
    'dashboard.form.displayName': '显示名称',
    'dashboard.form.firstName': '名字',
    'dashboard.form.lastName': '姓氏',
    'dashboard.form.location': '位置',
    'dashboard.form.bio': '个人简介',
    'dashboard.passport.title': '球员护照',
    'dashboard.stats.rankingPoints': '排名积分',
    'dashboard.stats.streak': '连胜',
    'dashboard.stats.passportCode': '护照代码',
    'dashboard.stats.tapToCopy': '点击复制',
    'dashboard.rankings.noData': '无排名数据',
    'dashboard.rankings.playMatches': '开始比赛以建立您的排名',
    'dashboard.rankings.systemVersion': 'PCP全球排名系统 v2.0 (多组别)',
    'dashboard.rankings.eligibleCategories': '符合条件的类别',
    'dashboard.form.selectPaddleBrand': '选择球拍品牌',
    'dashboard.form.paddleModel': '球拍型号',
    'dashboard.form.coachBio': '教练简介',
    'dashboard.form.coachBioPlaceholder': '描述您的教练理念和经验...',
    'dashboard.form.experienceYears': '教练年限',
    'dashboard.form.hourlyRate': '小时费率 ($)',
    'dashboard.form.specialties': '专长',
    'dashboard.form.specialtiesPlaceholder': '例如：初学者训练、比赛准备、技术分析',
    'dashboard.form.certifications': '认证',
    'dashboard.form.certificationsPlaceholder': '例如：PPR认证、3级教练员、美国匹克球认证',
    'dashboard.form.externalRatings': '外部评级',
    'dashboard.form.duprRating': 'DUPR评级',
    'dashboard.form.usaPickleballId': '美国匹克球ID',
    'dashboard.form.ifpRating': 'IFP评级',
    'dashboard.form.iptpaRating': 'IPTPA评级',
    'dashboard.form.physicalInfo': '身体信息',
    'dashboard.form.height': '身高 (cm)',
    'dashboard.form.reach': '臂展 (cm)',
    'dashboard.form.yearOfBirth': '出生年份',
    'dashboard.form.gender': '性别',
    'dashboard.form.selectGender': '选择性别',
    'dashboard.form.male': '男',
    'dashboard.form.female': '女',
    'dashboard.form.other': '其他',
    'dashboard.form.preferNotToSay': '不愿透露',
    'dashboard.form.cancel': '取消',
    'dashboard.form.saveChanges': '保存更改',
    'dashboard.form.saving': '保存中...',

    // Pickle Points
    'dashboard.picklePoints.title': '您的数字泡菜球货币',
    'dashboard.picklePoints.description': '泡菜积分是您在泡菜球社区中活跃所获得的奖励。通过比赛、完善资料、参加锦标赛以及与其他球员互动来赚取积分。',
    'dashboard.picklePoints.winMatches': '获胜比赛',
    'dashboard.picklePoints.winMatchesPoints': '+15-25 分',
    'dashboard.picklePoints.profileUpdates': '资料更新',
    'dashboard.picklePoints.profileUpdatesPoints': '+5-10 分',
    'dashboard.picklePoints.joinTournaments': '参加锦标赛',
    'dashboard.picklePoints.joinTournamentsPoints': '+20-50 分',
    'dashboard.picklePoints.dailyActivity': '每日活动',
    'dashboard.picklePoints.dailyActivityPoints': '+3-8 分',
    'dashboard.picklePoints.redeemTitle': '兑换奖励',
    'dashboard.picklePoints.redeemDescription': '使用您的积分兑换我们合作商家的专属奖励：',
    'dashboard.picklePoints.redeemCourt': '球场时间折扣',
    'dashboard.picklePoints.redeemEquipment': '设备和装备',
    'dashboard.picklePoints.redeemTournament': '锦标赛报名费',
    'dashboard.picklePoints.redeemCoaching': '教练课程',
    'dashboard.picklePoints.redeemEvents': '特殊活动准入',
    'dashboard.picklePoints.disclaimer': '积分通过验证活动获得，不能在账户间转让。',
    'dashboard.picklePoints.totalPoints': '总积分',
    'dashboard.picklePoints.matchWins': '比赛获胜',
    'dashboard.picklePoints.participation': '参与',
    'dashboard.picklePoints.profileBonus': '资料奖励',
    'dashboard.picklePoints.system': '系统',
    'dashboard.picklePoints.hybrid': '混合',
    'dashboard.picklePoints.spendPoints': '消费积分',
    'dashboard.picklePoints.spendDescription': '用您的泡菜积分兑换专属奖励、商品和锦标赛报名费。',
    'dashboard.picklePoints.earnMore': '赚取更多',
    'dashboard.picklePoints.earnDescription': '通过挑战、推荐和社区活动发现赚取泡菜积分的新方式。',

    // Dashboard Tabs
    'dashboard.tabs.performance': '表现',
    'dashboard.tabs.recentMatches': '近期比赛',
    'dashboard.tabs.achievements': '成就',
    'dashboard.tabs.community': '社区',

    // Profile Completion Modal
    'profile.completion.title': '完善您的资料',
    'profile.completion.description': '通过添加您的姓名帮助其他球员认识您。目前在比赛历史中显示为"{username}"。',
    'profile.completion.firstNameLabel': '名字',
    'profile.completion.lastNameLabel': '姓氏',
    'profile.completion.firstNamePlaceholder': '输入您的名字',
    'profile.completion.lastNamePlaceholder': '输入您的姓氏',
    'profile.completion.skipForNow': '暂时跳过',
    'profile.completion.updateProfile': '更新资料',
    'profile.completion.missingInfo': '缺少信息',
    'profile.completion.provideBothNames': '请提供姓名',
    'profile.completion.profileUpdated': '资料已更新',
    'profile.completion.nameAddedSuccess': '您的姓名已成功添加到资料中！',
    'profile.completion.updateFailed': '更新失败',
    'profile.completion.updateError': '更新资料时出错，请重试。',

    // Performance Trends
    'dashboard.performance.title': '表现趋势',
    'dashboard.performance.overallRating': '总体评级',
    'dashboard.performance.passportCode': '护照代码',
    'dashboard.performance.notSet': '未设置',
    'dashboard.performance.hide': '隐藏',
    'dashboard.performance.show': '显示',
    'dashboard.performance.recentForm': '近期状态',
    'dashboard.performance.improving': '进步中',
    'dashboard.performance.pointsThisMonth': '本月积分',

    // Quick Actions
    'dashboard.quickActions.title': '快捷操作',
    'dashboard.quickActions.recordMatch': '记录新比赛',
    'dashboard.quickActions.manageCoachProfile': '管理教练资料',
    'dashboard.quickActions.becomeCoach': '成为教练',
    'dashboard.quickActions.findTrainingFacilities': '寻找训练设施',
    'dashboard.quickActions.findCoaches': '寻找教练',
    'dashboard.quickActions.joinTournament': '参加锦标赛',
    'dashboard.quickActions.findPlayers': '寻找球员',

    // Landing Page
    'landing.brand': 'Pickle+',
    'landing.nav.features': '功能',
    'landing.nav.benefits': '优势',
    'landing.nav.community': '社区',
    'landing.nav.dashboard': '仪表板',
    'landing.nav.getStarted': '开始使用',
    'landing.hero.badge': '新平台现已可用',
    'landing.hero.title': '一个护照。',
    'landing.hero.titleHighlight': '每个球场。',
    'landing.hero.titleEnd': '您的真实排名。',
    'landing.hero.subtitle1': '第一个由球员为球员打造的透明排名系统。',
    'landing.hero.subtitle2': '没有黑盒。没有隐藏算法。',
    'landing.hero.getStarted': '开始您的球员之旅',
    'landing.hero.achievementBadge': '100%平台能力达成',
    'landing.hero.seeRanking': '了解排名系统如何运作',

    // Ranking Section
    'landing.ranking.title': '公平·透明·经验证',
    'landing.ranking.subtitle': '真正合理的年龄调整排名。采用精密算法，重视技能胜过人口统计。',

    // Tier System  
    'landing.tiers.recreational': '休闲级',
    'landing.tiers.recreationalPoints': '0-299分',
    'landing.tiers.competitive': '竞技级', 
    'landing.tiers.competitivePoints': '300-999分',
    'landing.tiers.elite': '精英级',
    'landing.tiers.elitePoints': '1000-1799分',
    'landing.tiers.professional': '职业级',
    'landing.tiers.professionalPoints': '1800+分',

    // Philosophy Section
    'landing.philosophy.title': '我们的排名理念',
    'landing.philosophy.subtitle': '每位球员都应该获得公平的机会。我们的算法认识到技能超越年龄、性别和比赛频率。',

    // Features
    'landing.features.performanceTitle': '表现权重',
    'landing.features.performanceDesc': '锦标赛胜利比休闲比赛权重更大，反映竞技成就。',
    'landing.features.ageTitle': '年龄平衡',
    'landing.features.ageDesc': '周到的调整确保各年龄段球员都能在其同龄人中有意义地竞争。',
    'landing.features.activityTitle': '活跃度保护',
    'landing.features.activityDesc': '智能衰减系统即使在忙碌生活期间也能维护您的排名。',

    // Result Section
    'landing.result.title': '结果：真正的竞技平衡',
    'landing.result.description': '25岁的大学运动员和55岁的周末勇士都能获得反映其在各自竞技背景下技能的排名。',

    // Additional Features
    'landing.features.ageGroupTitle': '年龄组公平性',
    'landing.features.ageGroupDesc': '自动年龄倍数确保各代人之间的公平竞争，具有经过验证的数学平衡。',
    'landing.features.genderTitle': '性别平衡系统',
    'landing.features.genderDesc': '针对发展中球员的跨性别奖励系统，在精英级别具有竞技平等。',
    'landing.features.decayTitle': '衰减保护',
    'landing.features.decayDesc': '特定等级活动要求，增强职业加权系统。',

    // Passport Section
    'landing.passport.title1': '您的数字化',
    'landing.passport.title2': '球员护照',
    'landing.passport.subtitle': '从0%到冠军地位。通过有意义的里程碑、泡菜积分奖励和完整的档案进展来追踪您的旅程。',
    'landing.passport.feature1': '二维码球场签到',
    'landing.passport.feature2': '实时排名更新',
    'landing.passport.feature3': '里程碑奖励系统',
    'landing.passport.feature4': '跨平台兼容性',
    'landing.passport.createButton': '创建您的护照',
    'landing.passport.learnMore': '了解更多关于排名',

    // Community Section
    'landing.community.title': '由社区打造',
    'landing.community.subtitle': '在球员、教练和锦标赛总监的意见参与下开发，创造匹克球应得的排名系统。',
    'landing.community.stat1': '平台就绪',
    'landing.community.stat2': '分级系统',
    'landing.community.stat3': '年龄与性别平衡',
    'landing.community.joinButton': '加入革命',

    // Footer
    'landing.footer.copyright': '© 2025 Pickle+. 匹克球排名系统的未来。',
    'landing.sport': '匹克球',
    'landing.hero.description': '加入数千名球员，使用先进的分析、教练工具和社区功能来提升您的匹克球表现。',
    'landing.hero.startFree': '今天免费开始',
    'landing.hero.watchDemo': '观看演示',
    'landing.hero.goToDashboard': '前往仪表板',
    'landing.hero.feature1': '永久免费',
    'landing.hero.feature2': '2分钟设置',
    'landing.hero.card.title': '球员统计',
    'landing.hero.card.rating': 'DUPR评级',
    'landing.hero.card.matches': '比赛',
    'landing.hero.card.rank': '本地排名',
    'landing.hero.card.points': '积分',
    'landing.features.title': '您需要的一切以实现卓越',
    'landing.features.description': '专为帮助各个水平的球员提升技能并与社区建立联系而设计的综合工具。',
    'landing.features.analytics.title': '智能分析',
    'landing.features.analytics.description': '跟踪表现指标，分析游戏模式，并获得个性化见解以改进您的游戏。',
    'landing.features.community.title': '活跃社区',
    'landing.features.community.description': '与全球球员建立联系，寻找练习伙伴，参加本地锦标赛和活动。',
    'landing.features.tournaments.title': '锦标赛管理',
    'landing.features.tournaments.description': '通过我们的综合锦标赛管理系统组织、参加和跟踪锦标赛。',
    'landing.features.coaching.title': '专业教练',
    'landing.features.coaching.description': '获得认证教练的指导，获取个性化训练计划，并跟踪您的技能发展进度。',
    'landing.features.mobile.title': '移动就绪',
    'landing.features.mobile.description': '功能齐全的移动应用程序，可随时随地跟踪比赛、查看统计数据并与社区保持联系。',
    'landing.features.progress.title': '进度跟踪',
    'landing.features.progress.description': '通过详细的分析和成就系统监控您的长期改进。',
    'landing.benefits.title': '为什么球员选择Pickle+',
    'landing.benefits.description': '我们的平台将前沿技术与社区驱动的功能相结合，创造终极匹克球体验。',
    'landing.benefits.benefit1.title': '数据驱动的改进',
    'landing.benefits.benefit1.description': '通过全面的表现分析对您的训练做出明智决策。',
    'landing.benefits.benefit2.title': '全球社区访问',
    'landing.benefits.benefit2.description': '与全球球员建立联系，参加符合您技能水平的活动。',
    'landing.benefits.benefit3.title': '专业成长',
    'landing.benefits.benefit3.description': '获得教练认证计划，作为球员或教练发展您的技能。',
    'landing.benefits.stats.title': '平台影响',
    'landing.benefits.stats.improvement': '球员改进',
    'landing.benefits.stats.players': '活跃球员',
    'landing.benefits.stats.setup': '快速设置',
    'landing.benefits.stats.tracking': '比赛跟踪',
    // Removed duplicate - keeping the original above
    'landing.community.description': '与来自世界各地的热情匹克球球员建立联系，他们正在通过数据驱动的见解改变自己的游戏。',
    'landing.community.countries': '代表国家',
    'landing.community.activeUsers': '活跃用户',
    'landing.community.matchesTracked': '跟踪的比赛',
    'landing.community.joinNow': '加入社区',
    'landing.community.goToDashboard': '前往仪表板',
    'landing.footer.description': '为匹克球球员提供跟踪、改进和连接的综合平台。',
    'landing.footer.product': '产品',
    'landing.footer.features': '功能',
    'landing.footer.pricing': '定价',
    'landing.footer.tutorials': '教程',
    'landing.footer.company': '公司',
    'landing.footer.about': '关于',
    'landing.footer.contact': '联系',
    'landing.footer.privacy': '隐私',
    'landing.footer.support': '支持',
    'landing.footer.help': '帮助中心',
    'landing.footer.community': '社区',
    'landing.footer.updates': '更新',
    'landing.footer.rights': '版权所有。',
    
    // Authentication
    'auth.backToHome': '返回首页',
    'auth.welcomeBack': '欢迎回来',
    'auth.createPassport': '创建您的通行证',
    'auth.signInDescription': '登录以访问您的球员仪表板',
    'auth.joinRevolution': '加入透明排名革命',
    'auth.signIn': '登录',
    'auth.createAccount': '创建账户',
    'auth.usernameOrEmail': '用户名或邮箱',
    'auth.usernamePlaceholder': '请输入用户名或邮箱',
    'auth.password': '密码',
    'auth.passwordPlaceholder': '请输入您的密码',
    'auth.rememberMe': '记住我30天',
    'auth.loggingIn': '登录中...',
    'auth.signInToDashboard': '登录到仪表板',
    'auth.firstName': '名字',
    'auth.firstNamePlaceholder': '张',
    'auth.lastName': '姓氏',
    'auth.lastNamePlaceholder': '三',
    'auth.username': '用户名',
    'auth.usernamePlaceholderRegister': '选择一个唯一的用户名',
    'auth.email': '电子邮件',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.createPassword': '创建强密码',
    'auth.confirmPassword': '确认密码',
    'auth.confirmPasswordPlaceholder': '确认您的密码',
    'auth.birthYear': '出生年份',
    'auth.birthYearPlaceholder': '1990',
    'auth.skillLevel': '技能水平',
    'auth.selectLevel': '选择水平',
    'auth.beginner': '初学者',
    'auth.intermediate': '中级',
    'auth.advanced': '高级',
    'auth.expert': '专家',
    'auth.location': '位置（可选）',
    'auth.locationPlaceholder': '城市，州/国家',
    'auth.agreeToTerms': '我同意服务条款和隐私政策',
    'auth.creatingAccount': '创建账户中...',
    'auth.createPassportButton': '创建我的球员通行证',
    'auth.signingIn': '正在登录...',
    'auth.creatingPassport': '正在创建您的球员通行证...',
    'auth.forgotPassword': '忘记密码？',
    'auth.dontHaveAccount': '没有账户？',
    'auth.alreadyHaveAccount': '已有账户？',
    'auth.signUp': '注册',
    'auth.signIn': '登录',
    
    // Complete auth translations - removing duplicates
    'auth.firstNameLabel': '名字',
    'auth.firstNamePlaceholder': '输入您的名字',
    'auth.lastNameLabel': '姓氏',
    'auth.lastNamePlaceholder': '输入您的姓氏',
    'auth.usernameLabel': '用户名',
    'auth.usernamePlaceholder': '选择用户名',
    'auth.authUsernamePlaceholder': '选择用户名',
    'auth.emailLabel': '邮箱地址',
    'auth.emailPlaceholder': '输入您的邮箱地址',
    'auth.passwordLabel': '密码',
    'auth.passwordPlaceholder': '输入您的密码',
    'auth.confirmPasswordLabel': '确认密码',
    'auth.confirmPasswordPlaceholder': '确认您的密码',
    'auth.yearOfBirthLabel': '出生年份',
    'auth.yearOfBirthPlaceholder': '例如: 1990',
    'auth.location': '国家（可选）',
    'auth.countryPlaceholder': '选择国家...',
    'auth.searchCountries': '搜索国家...',
    'auth.noCountryFound': '未找到国家。',
    'auth.playingSinceLabel': '何时开始打匹克球？',
    'auth.playingSincePlaceholder': '例如: 2 年',
    'auth.skillLevelLabel': '您的技能水平',
    'auth.skillLevelPlaceholder': '例如: 初学者',
    'auth.agreeToTerms': '我同意条款和条件',
    'auth.createAccount': '创建账户',
    'auth.creatingAccount': '正在创建账户...',
    'auth.registerSuccess': '注册成功',
    'auth.registerSuccessDescription': '欢迎来到 Pickle+！您的账户已创建。',
    'auth.registerError': '注册失败',
    'auth.registerErrorDescription': '创建账户时出错。请重试。',
    'auth.passwordMismatch': '密码不匹配',
    'auth.usernameOrEmail': '用户名或邮箱',
    'auth.rememberMe': '记住我',
    'auth.loggingIn': '正在登录...',
    'auth.joinPicklePlus': '加入 Pickle+',
    'auth.loginPlaceholder': '输入用户名或邮箱',
    
    // Profile & Player Info
    'profile.personalInfo': '个人信息',
    'profile.statistics': '统计数据',
    'profile.equipment': '装备',
    'profile.preferences': '偏好设置',
    'profile.achievements': '成就',
    'profile.updatePhoto': '更新照片',
    'profile.height': '身高',
    'profile.weight': '体重',
    'profile.dominantHand': '惯用手',
    'profile.playingStyle': '比赛风格',
    
    // Dashboard Stats
    'stats.duprRating': 'DUPR评级',
    'stats.winRate': '胜率',
    'stats.matches': '比赛',
    'stats.loading': '加载中...',

    
    // Training & Facilities
    'training.centers': '训练中心',
    'training.schedule': '课程安排',
    'training.bookClass': '预订课程',
    'training.history': '训练历史',
    'training.instructor': '教练',
    'training.duration': '时长',
    'training.capacity': '容量',
    'training.available': '可用',
    'training.full': '已满',
    
    // Match Recording
    'match.record': '记录比赛',
    'match.opponent': '对手',
    'match.score': '比分',
    'match.result': '结果',
    'match.win': '胜利',
    'match.loss': '失败',
    'match.date': '日期',
    'match.format': '比赛形式',
    'match.singles': '单打',
    'match.doubles': '双打',
    'match.mixed': '混双',
    
    // Time & Status
    'time.today': '今天',
    'time.yesterday': '昨天',
    'time.thisWeek': '本周',
    'time.thisMonth': '本月',
    'time.allTime': '全部时间',
    'status.online': '在线',
    'status.offline': '离线',
    'status.active': '活跃',
    'status.inactive': '不活跃',
    'status.available': '可用',
    'status.busy': '忙碌',
    
    // Equipment & Gear
    'equipment.paddle': '球拍',
    'equipment.shoes': '球鞋',
    'equipment.apparel': '服装',
    'equipment.accessories': '配件',
    'equipment.brand': '品牌',
    'equipment.model': '型号',
    'equipment.primary': '主要',
    'equipment.backup': '备用',
    
    // Notifications & Messages
    'notification.success': '成功',
    'notification.error': '错误',
    'notification.warning': '警告',
    'notification.info': '信息',
    'notification.copied': '已复制',
    'notification.saved': '已保存',
    'notification.updated': '已更新',
    'notification.deleted': '已删除',
    
    // Actions & Buttons
    'action.view': '查看',
    'action.edit': '编辑',
    'action.delete': '删除',
    'action.add': '添加',
    'action.remove': '移除',
    'action.update': '更新',
    'action.refresh': '刷新',
    'action.search': '搜索',
    'action.filter': '筛选',
    'action.sort': '排序',
    'action.export': '导出',
    'action.import': '导入',
    
    // Settings & Configuration
    'settings.general': '常规设置',
    'settings.privacy': '隐私设置',
    'settings.notifications': '通知设置',
    'settings.language': '语言设置',
    'settings.theme': '主题设置',
    'settings.account': '账户设置',
    'settings.security': '安全设置',
    'settings.preferences': '偏好设置',
    
    // Coaching
    'coaching.pcpProgramme': '教练简介',
    
    // Additional auth content (removed to avoid duplicates)

    // Navigation Items
    'nav.features': '功能',
    'nav.pcpCertification': 'PCP认证',
    'nav.developmentHub': '发展中心',
    'nav.adminPanel': '管理面板',
    'nav.home': '首页',
    'nav.community': '社区',
    'nav.coaching': '教练',
    'nav.profile': '个人资料'
  }
};

// Detect browser language
const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language || navigator.languages[0];
  if (browserLang.startsWith('zh')) {
    return 'zh-CN';
  }
  return 'en';
};

// Get stored language or detect from browser
const getInitialLanguage = (): Language => {
  const stored = localStorage.getItem('pickle-plus-language') as Language;
  if (stored && (stored === 'en' || stored === 'zh-CN')) {
    return stored;
  }
  return detectBrowserLanguage();
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pickle-plus-language', lang);
  };

  // Translation function with fallback
  const t = (key: string, fallback?: string): string => {
    try {
      const currentTranslations = translations[language];
      if (!currentTranslations) {
        console.warn(`No translations found for language: ${language}`);
        return fallback || key;
      }
      
      const translation = currentTranslations[key];
      
      if (translation && translation !== '') {
        return translation;
      }
      
      // Fallback to English if key doesn't exist in current language
      if (language !== 'en') {
        const englishTranslations = translations['en'];
        const englishTranslation = englishTranslations?.[key];
        if (englishTranslation && englishTranslation !== '') {
          console.warn(`Using English fallback for key: ${key}`);
          return englishTranslation;
        }
      }
      
      // Return fallback or key if no translation found
      console.warn(`No translation found for key: ${key}`);
      return fallback || key;
    } catch (error) {
      console.error('Translation function error:', error);
      return fallback || key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}